---
name: CI
on: push
jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit:latest
        with:
          cc: gcc
          checks: build test install warnings
        env:
          CONAN_RUN_TESTS: 1
  build-gcc-concepts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit:latest
        with:
          cc: gcc
          cmakeflags: -Dconcore.use2020=yes
          checks: build test install warnings
        env:
          CONAN_RUN_TESTS: 1
  build-clang:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          cc: [ clang-7, clang-10 ]
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit:latest
        with:
          cc: ${{ matrix.cc }}
          conanflags: -s compiler.libcxx=libstdc++11
          checks: build test
        env:
          CONAN_RUN_TESTS: 1
  build-clang-cxx14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit:latest
        with:
          cc: clang-7
          cxxflags: -std=c++14
          conanflags: -s compiler.libcxx=libstdc++11
          checks: build test
        env:
          CONAN_RUN_TESTS: 1
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit:latest
        with:
          cc: gcc-9
          checks: cppcheck clang-tidy
          clangtidyflags: '-quiet'
          cppcheckflags: '--enable=warning,style,performance,portability --inline-suppr'
        env:
          CONAN_RUN_TESTS: 1
#  clang-format:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - uses: docker://lucteo/action-cxx-toolkit:latest
#        with:
#          checks: clang-format
#          clangformatdirs: src test
  sanitizer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit:latest
        with:
          checks: sanitize=address sanitize=undefined
        env:
          CONAN_RUN_TESTS: 1
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit:latest
        with:
          checks: coverage=codecov
        env:
          CONAN_RUN_TESTS: 1
          GITHUB_ACTION: ${GITHUB_ACTION}
          GITHUB_REF: ${GITHUB_REF}
          GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
          GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}
          GITHUB_SHA: ${GITHUB_SHA}
          GITHUB_RUN_ID: ${GITHUB_RUN_ID}
