---
name: CI
on: push
jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: lucteo/action-cxx-toolkit@master
        with:
          cc: gcc
          checks: build test install warnings
  build-clang:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          cc: [ clang-7, clang-10 ]
    steps:
      - uses: actions/checkout@master
      - uses: lucteo/action-cxx-toolkit@master
        with:
          cc: ${{ matrix.cc }}
          conanflags: -s compiler.libcxx=libstdc++11
          checks: build test
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: lucteo/action-cxx-toolkit@master
        with:
          cc: gcc-9
          checks: cppcheck clang-tidy
          clangtidyflags: '-quiet'
          cppcheckflags: '--enable=warning,style,performance,portability --inline-suppr'
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: lucteo/action-cxx-toolkit@master
        with:
          checks: clang-format
          clangformatdirs: src include test
  sanitizer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: lucteo/action-cxx-toolkit@master
        with:
          checks: sanitize=address sanitize=undefined
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: lucteo/action-cxx-toolkit@master
        with:
          checks: coverage=codecov
        env:
          GITHUB_ACTION: ${GITHUB_ACTION}
          GITHUB_REF: ${GITHUB_REF}
          GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
          GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}
          GITHUB_SHA: ${GITHUB_SHA}
          GITHUB_RUN_ID: ${GITHUB_RUN_ID}
